networks:
  default: localnet
  localnet:
    url: http://127.0.0.1:4000/api
    leader_only: false
  studionet: {}
  testnet_asimov:
    accounts:
      - ${ACCOUNT_PRIVATE_KEY_1}
    from: ${ACCOUNT_PRIVATE_KEY_1}
  testnet_bradbury:
    accounts:
      - ${ACCOUNT_PRIVATE_KEY_1}
    from: ${ACCOUNT_PRIVATE_KEY_1}
paths:
  contracts: contracts
  artifacts: artifacts
environment: .env
